"""Storage layer: SQLite schema, migrations and queries.

Design notes
------------
* Single SQLite file, no external database — the whole app must run from one
  container with one volume.
* All timestamps are stored as *local wall-clock* strings ("floating time"),
  never UTC.  A personal calendar that says "09:00" must keep saying 09:00 no
  matter which timezone the phone is in; this is also what makes the generated
  .ics feeds behave correctly in Apple Calendar without shipping a VTIMEZONE.
* Schema is English so the project can be published as-is; the user-facing
  language lives in the UI layer only.
* Recurring items are never materialised.  A recurring series is one row in
  `events`; per-occurrence edits and deletions live in `event_overrides`,
  keyed by the *original* occurrence start date.  This is the same model the
  iCalendar standard uses (RECURRENCE-ID / EXDATE), so the .ics feed can
  express every exception losslessly.
"""
from __future__ import annotations

import os
import sqlite3
import threading
from contextlib import contextmanager
from datetime import date, datetime, timedelta

DB_PATH = os.environ.get("DB_PATH", "/data/calendar.db")

_local = threading.local()

SCHEMA = """
PRAGMA journal_mode=WAL;

CREATE TABLE IF NOT EXISTS calendars(
  id         INTEGER PRIMARY KEY,
  name       TEXT    NOT NULL,
  color      TEXT    NOT NULL DEFAULT '#5b9dff',
  position   INTEGER NOT NULL DEFAULT 0,
  visible    INTEGER NOT NULL DEFAULT 1,
  created_at TEXT    NOT NULL DEFAULT (datetime('now','localtime'))
);

CREATE TABLE IF NOT EXISTS events(
  id          INTEGER PRIMARY KEY,
  calendar_id INTEGER REFERENCES calendars(id) ON DELETE SET NULL,
  title       TEXT    NOT NULL,
  notes       TEXT,
  location    TEXT,
  -- 'YYYY-MM-DD HH:MM' for timed, 'YYYY-MM-DD' for all-day
  starts_at   TEXT    NOT NULL,
  ends_at     TEXT    NOT NULL,
  all_day     INTEGER NOT NULL DEFAULT 0,
  -- '', 'daily', 'weekly', 'monthly', 'yearly'
  repeat      TEXT    NOT NULL DEFAULT '',
  repeat_every INTEGER NOT NULL DEFAULT 1,
  repeat_until TEXT,
  -- weekly only: comma-separated weekdays '0,2' (0=Monday), '' = start's day
  repeat_days TEXT    NOT NULL DEFAULT '',
  -- per-event colour; NULL/'' falls back to the calendar colour
  color       TEXT,
  -- comma-separated minutes-before-start, e.g. '10' or '10,1440'; '' = none
  reminders   TEXT    NOT NULL DEFAULT '',
  -- soft delete: set on delete, purged after 24h (the "Silinenler" bin)
  deleted_at  TEXT,
  uid         TEXT    NOT NULL,
  created_at  TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
  updated_at  TEXT    NOT NULL DEFAULT (datetime('now','localtime'))
);
CREATE INDEX IF NOT EXISTS ix_events_span ON events(starts_at, ends_at);

-- Per-occurrence exceptions for recurring events ("this event only" edits).
-- occ_date is the ORIGINAL occurrence start date generated by the rule —
-- moving an occurrence changes starts_at here, never occ_date, so the row
-- keeps matching the rule slot it excepts (exactly like RECURRENCE-ID).
CREATE TABLE IF NOT EXISTS event_overrides(
  id         INTEGER PRIMARY KEY,
  event_id   INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  occ_date   TEXT    NOT NULL,
  cancelled  INTEGER NOT NULL DEFAULT 0,
  starts_at  TEXT,
  ends_at    TEXT,
  title      TEXT,
  notes      TEXT,
  location   TEXT,
  color      TEXT,
  reminders  TEXT,
  all_day    INTEGER,
  UNIQUE(event_id, occ_date)
);
CREATE INDEX IF NOT EXISTS ix_overrides_event ON event_overrides(event_id, occ_date);

CREATE TABLE IF NOT EXISTS task_lists(
  id         INTEGER PRIMARY KEY,
  name       TEXT    NOT NULL,
  color      TEXT    NOT NULL DEFAULT '#3fbf7f',
  position   INTEGER NOT NULL DEFAULT 0,
  created_at TEXT    NOT NULL DEFAULT (datetime('now','localtime'))
);

CREATE TABLE IF NOT EXISTS tasks(
  id           INTEGER PRIMARY KEY,
  list_id      INTEGER NOT NULL REFERENCES task_lists(id) ON DELETE CASCADE,
  parent_id    INTEGER REFERENCES tasks(id) ON DELETE CASCADE,
  title        TEXT    NOT NULL,
  notes        TEXT,
  due_date     TEXT,              -- 'YYYY-MM-DD' or NULL
  due_time     TEXT,              -- 'HH:MM' or NULL (only meaningful with due_date)
  done         INTEGER NOT NULL DEFAULT 0,
  done_at      TEXT,
  position     INTEGER NOT NULL DEFAULT 0,
  repeat       TEXT    NOT NULL DEFAULT '',
  repeat_every INTEGER NOT NULL DEFAULT 1,
  -- weekly only: comma-separated weekdays '0,2' (0=Monday), '' = due's day
  repeat_days  TEXT    NOT NULL DEFAULT '',
  -- occurrences removed/detached from the series: comma-separated 'YYYY-MM-DD'
  skip_dates   TEXT    NOT NULL DEFAULT '',
  deleted_at   TEXT,
  uid          TEXT    NOT NULL,
  created_at   TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
  updated_at   TEXT    NOT NULL DEFAULT (datetime('now','localtime'))
);
CREATE INDEX IF NOT EXISTS ix_tasks_list ON tasks(list_id, position);
CREATE INDEX IF NOT EXISTS ix_tasks_due  ON tasks(due_date);
"""

# Columns added after the first release.  ALTER TABLE is idempotent-guarded
# by a PRAGMA table_info check, so upgrading an existing database is safe and
# a fresh database (already created with the full schema above) is untouched.
MIGRATIONS = (
    ("events", "repeat_days", "ALTER TABLE events ADD COLUMN repeat_days TEXT NOT NULL DEFAULT ''"),
    ("events", "color", "ALTER TABLE events ADD COLUMN color TEXT"),
    ("events", "reminders", "ALTER TABLE events ADD COLUMN reminders TEXT NOT NULL DEFAULT ''"),
    ("tasks", "repeat_days", "ALTER TABLE tasks ADD COLUMN repeat_days TEXT NOT NULL DEFAULT ''"),
    ("events", "deleted_at", "ALTER TABLE events ADD COLUMN deleted_at TEXT"),
    ("tasks", "deleted_at", "ALTER TABLE tasks ADD COLUMN deleted_at TEXT"),
    ("tasks", "skip_dates", "ALTER TABLE tasks ADD COLUMN skip_dates TEXT NOT NULL DEFAULT ''"),
)


def connect() -> sqlite3.Connection:
    """One connection per thread; FastAPI runs sync handlers in a threadpool."""
    conn = getattr(_local, "conn", None)
    if conn is None:
        os.makedirs(os.path.dirname(DB_PATH) or ".", exist_ok=True)
        conn = sqlite3.connect(DB_PATH, timeout=15)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys=ON")
        _local.conn = conn
    return conn


@contextmanager
def tx():
    conn = connect()
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise


def init() -> None:
    with tx() as c:
        c.executescript(SCHEMA)
        for table, col, sql in MIGRATIONS:
            cols = {r[1] for r in c.execute(f"PRAGMA table_info({table})")}
            if col not in cols:
                c.execute(sql)
        # Seed defaults only on a genuinely empty database, so a restart never
        # re-creates lists the user deleted on purpose.
        if not c.execute("SELECT 1 FROM calendars LIMIT 1").fetchone():
            c.execute("INSERT INTO calendars(name,color,position) VALUES (?,?,0)",
                      ("Personal", "#5b9dff"))
        if not c.execute("SELECT 1 FROM task_lists LIMIT 1").fetchone():
            c.execute("INSERT INTO task_lists(name,color,position) VALUES (?,?,0)",
                      ("Tasks", "#3fbf7f"))
    # Fold the WAL into the main file at every boot.  Without this, hours of
    # writes can live only in the -wal (uvicorn is SIGKILLed, connections
    # never close cleanly) — recoverable, but a single mismatched header away
    # from being painful.  Learned the forensic way on 16 Aug 2026.
    connect().execute("PRAGMA wal_checkpoint(TRUNCATE)")


def new_uid(prefix: str) -> str:
    """Stable per-item UID for .ics. Random enough, no external dependency."""
    return f"{prefix}-{os.urandom(8).hex()}@calendar.local"


# ── date helpers ────────────────────────────────────────────────────────────
DATE_FMT = "%Y-%m-%d"
DT_FMT = "%Y-%m-%d %H:%M"


def parse_dt(value: str) -> datetime:
    value = (value or "").strip().replace("T", " ")
    if len(value) <= 10:
        return datetime.strptime(value[:10], DATE_FMT)
    return datetime.strptime(value[:16], DT_FMT)


def fmt_dt(value: datetime, all_day: bool) -> str:
    return value.strftime(DATE_FMT if all_day else DT_FMT)


def week_start(d: date, first_weekday: int = 0) -> date:
    """Monday-first by default (first_weekday=0); Sunday-first with 6."""
    shift = (d.weekday() - first_weekday) % 7
    return d - timedelta(days=shift)
